const database = {
  recette1: {
    titre: " La Bouillabaisse",
    carousselImg: [
      "img/bouillabaisse-carroussel1.jpeg",
      "img/bouillabaisse-carroussel2.jpg",
      "img/bouillabaisse-carroussel3.jpg",
      "img/bouillabaisse-carroussel4.jpg",
    ],
    ingredients: [
      "kg de poissons de mer",
      "g de fenouil",
      "g de celeri",
      "kg de rascasse",
      "langoustes",
      "kg de rouget grondin",
      "kg de pommes de terre",
    ],
    quantites: [0.25, 80, 20, 0.25, 1, 0.25, 0.5],
    imgEtapes: [
      "img/fenouil.jpg",
      "img/moule.jpg",
      "img/baies.jpg",
      "img/poisson-bouillabaisse.jpeg",
      "img/laurier.jpg",
      "img/epices.jpeg",
    ],
    niveau: "Moyen",
    niveauVal: 2,
  },
  recette2: {
    titre: " La Choucroute",
    carousselImg: [
      "img/choucroute1.jpg",
      "img/choucroute2.jpg",
      "img/choucroute3.jpg",
      "img/choucroute4.jpg",
    ],
    ingredients: [
      "chou à choucroute",
      "oignons",
      "grains de genièvre",
      "500 g de rôti de porc",
      "saucisse de Strasbourg",
      " bouteille de Riesling",
      "kg de patates",
    ],
    quantites: [0.5, 150, 4, 0.5, 1, 0.25, 0.5],
    imgEtapes: [
      "img/choux.jpg",
      "img/saucisse.jpg",
      "img/baies.jpg",
      "img/patate2.jpg",
      "img/muscade.jpeg",
      "img/choucroute-final.jpg",
    ],
    niveau: "Difficile",
    niveauVal: 3,
  },
  recette3: {
    titre: " Le Boeuf Bourguignon",
    carousselImg: [
      "img/boeuf-bourguignon1.jpeg",
      "img/boeuf-bourguignon2.jpg",
      "img/boeuf-bourguignon3.jpeg",
      "img/boeuf-bourguignon4.jpg",
    ],
    ingredients: [
      "kg de viande de boeuf",
      "oignons",
      "carottes",
      "cl de vin rouge",
      "g de champignons de Paris",
      "g de largons",
      "gousse d'ail",
    ],
    quantites: [0.25, 0.5, 1, 10, 50, 25, 0.5],
    imgEtapes: [
      "img/carotte.jpg",
      "img/decoupe.jpg",
      "img/plat-final.jpg",
      "img/sauce-vin.jpg",
      "img/sel-poivre.jpeg",
      "img/riz.jpeg",
    ],
    niveau: "Moyen",
    niveauVal: 2,
  },
  recette4: {
    titre: " Le Gratin Dauphinois",
    carousselImg: [
      "img/gratin1.jpg",
      "img/gratin2.jpg",
      "img/gratin3.jpg",
      "img/gratin4.jpg",
    ],
    ingredients: [
      "kg de pommes de terre",
      "cl de creme liquide",
      "cl de lait",
      "noisette de beurre",
      "gousse d'ail",
      "pincee de noix de muscade",
    ],
    quantites: [0.5, 30, 40, 1, 1, 1],
    imgEtapes: [
      "img/patate.jpg",
      "img/lait.jpg",
      "img/beurre.jpg",
      "img/ail.jpg",
      "img/muscade.jpeg",
      "img/gratin-final.jpeg",
    ],
    niveau: "Facile",
    niveauVal: 1,
  },
};

export const tableauRecettes = database;
